trigger:
  # Whenever someone pushes to master:
  branches:
    include:
    - master
  # Whenever a tag is pushed:
  tags:
    include:
    - v*

variables:
  # Install p2p in Docker container
  install_p2p: "pip install -r requirements.txt && pip install -e ."
  CIBW_BEFORE_BUILD: $(install_p2p)
  # On Linux, need to install Matplotlib depedencies in Docker container:
  CIBW_BEFORE_BUILD_LINUX: "yum -y install freetype-devel pkg-config libpng-devel && $(install_p2p)"
  # Skip building on Python 2.7 and 3.8 on all platforms
  CIBW_SKIP: "cp27-* cp38-*"

jobs:
- job: linux
  pool: {vmImage: 'Ubuntu-16.04'}
  steps: 
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.5
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.0.0
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
- job: macos
  pool: {vmImage: 'macOS-10.13'}
  steps: 
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.5
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.0.0
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
- job: windows
  pool: {vmImage: 'vs2017-win2016'}
  steps: 
    - task: UsePythonVersion@0
      inputs:
        versionSpec: 3.5
    - bash: |
        python -m pip install --upgrade pip
        pip install cibuildwheel==1.0.0
        cibuildwheel --output-dir wheelhouse .
    - task: PublishBuildArtifacts@1
      inputs: {pathtoPublish: 'wheelhouse'}
